channels:
- conda-forge
dependencies:
- python=3.12.4
- pip<=24.0
- pip:
  - mlflow==2.10.2
  - cloudpickle==3.1.1
  - numpy==1.26.3
  - packaging==23.2
  - pyyaml==6.0.2
  - scikit-learn==1.4.0
  - scipy==1.12.0
name: mlflow-env
